FROM python:3.11-slim

WORKDIR /app

# Cài đặt các thư viện hệ thống cần thiết
RUN apt-get update && apt-get install -y \
    gcc \
    libffi-dev \
    libssl-dev \
    && apt-get clean

RUN pip install --upgrade pip

# Copy requirements trước để tận dụng cache
# Copy toàn bộ source code
COPY ./Booking/requirements.txt /app/requirements.txt
COPY ./Booking /app/Booking
COPY ./jwt_shared /app/jwt_shared

# Cài đặt các dependencies
RUN pip install --no-cache-dir -r /app/requirements.txt


EXPOSE 8003

# Chạy migrate rồi khởi động uvicorn
CMD ["sh", "-c", "alembic -c Booking/alembic.ini upgrade head && uvicorn Booking.controller.main:app --host 0.0.0.0 --port 8003 --reload"]
