FROM python:3.11-slim

WORKDIR /app

# Copy requirements trước để tận dụng cache
COPY ./Report/requirements.txt /app/requirements.txt

# Copy toàn bộ source code
COPY ./jwt_shared /app/jwt_shared
COPY ./Report /app/Report

# Cài đặt các dependencies
RUN pip install --no-cache-dir -r /app/requirements.txt



ENV PYTHONPATH=/app
EXPOSE 8000

# Chạy ứng dụng bằng uvicorn
CMD ["uvicorn", "Report.controller.main:app", "--host", "0.0.0.0", "--port", "8009"]

