FROM python:3.11-slim

WORKDIR /app

# Cài đặt các thư viện hệ thống cần thiết
RUN apt-get update && apt-get install -y \
    gcc \
    libffi-dev \
    libssl-dev \
    && apt-get clean

RUN pip install --upgrade pip

# Copy requirements trước để tận dụng cache
COPY ./Auth/requirements.txt /app/requirements.txt

# Cài đặt các dependencies
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy toàn bộ source code
COPY ./jwt_shared /app/jwt_shared
COPY ./Auth /app/Auth

COPY ./Auth/start.sh /app/start.sh
RUN chmod +x /app/start.sh

EXPOSE 8000

# Chạy ứng dụng bằng uvicorn
CMD ["./Auth/start.sh"]
