FROM python:3.11-slim

WORKDIR /app

# Copy requirements trước để tận dụng cache
COPY ./Notification/requirements.txt .

# Copy toàn bộ source code
COPY ./jwt_shared /app/jwt_shared
COPY ./Notification /app/Notification

# Cài đặt các dependencies
RUN pip install --no-cache-dir -r /app/requirements.txt



EXPOSE 8000

# Chạy ứng dụng bằng uvicorn
CMD ["uvicorn", "controller.main:app", "--host", "0.0.0.0", "--port", "8007", "--reload"]
