FROM python:3.11-slim

WORKDIR /app

# Copy requirements trước để tận dụng cache
COPY ./Notification/requirements.txt .

# Copy toàn bộ source code
COPY ./jwt_shared /app/jwt_shared
COPY ./Notification /app/Notification

# Cài đặt các dependencies
RUN pip install --no-cache-dir -r /app/requirements.txt
RUN chmod +x /app/Notification/start.sh


ENV PYTHONPATH=/app
EXPOSE 8000

# Chạy ứng dụng bằng uvicorn
CMD ["bash", "/app/Notification/start.sh"]

