FROM python:3.11-slim

WORKDIR /app

# Copy requirements trước để tận dụng cache
COPY requirements.txt .

# Cài đặt các dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy toàn bộ source code
COPY . .

EXPOSE 8000

# Chạy ứng dụng bằng uvicorn
CMD ["uvicorn", "controller.main:app", "--host", "0.0.0.0", "--port", "8005", "--reload"]
