FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    libffi-dev \
    libssl-dev \
    && apt-get clean

RUN pip install --upgrade pip

COPY ./Facility/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY ./Facility /app/Facility
COPY ./jwt_shared /app/jwt_shared

EXPOSE 8005

CMD ["uvicorn", "Facility.controller.main:app", "--host", "0.0.0.0", "--port", "8005", "--reload"]
