FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    libffi-dev \
    libssl-dev \
    && apt-get clean

RUN pip install --upgrade pip

COPY ./Court/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY ./Court /app/Court
COPY ./jwt_shared /app/jwt_shared

EXPOSE 8004

CMD ["sh", "-c", "alembic -c Court/alembic.ini upgrade head && uvicorn Court.controller.main:app --host 0.0.0.0 --port 8004 --reload"]
